/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.component;
//
//import dao.LoaiBan_DAO;
//import entity.Ban;
//import entity.LoaiBan;

import dao.LoaiBanDAO;
import dao.impl.LoaiBanDAOImpl;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import model.Ban;
import model.LoaiBan;

/**
 *
 * @author Thanh Tuan
 */
public class ItemTable extends javax.swing.JPanel {

    private JLabel tableLable = null;
    private Ban ban = null;
    private static Map<String, ImageIcon> imageCache = new HashMap<>();
    private LoaiBanDAO loaiBanDAO = new LoaiBanDAOImpl(LoaiBan.class);
    private LoaiBan loaiBan = null;
    private boolean isSelected = false;

    /**
     * Creates new form ItemTable
     */
    public ItemTable(JLabel tableLabel, Ban ban) {
        initComponents();
        this.tableLable = tableLabel;
        this.ban = ban;
        jPanel8.setBackground(Color.WHITE); // Màu nền mặc định
        loadBan();
    }

    public void loadBan() {
        SwingUtilities.invokeLater(() -> {
            imgLoad("/hinhAnh/table.png");
        });
        loaiBan = loaiBanDAO.findById(ban.getLoaiBan().getMaLB());
        imgTable.setToolTipText(ban.getMaBan());
        tableName.setToolTipText(ban.getMaBan());
        tableName.setText("Bàn " + ban.getSoBan() + " / " + loaiBan.getTenLB() + " (" + ban.getSoGhe() + ")");
    }

    public void deselect() {
        isSelected = false;
        jPanel8.setBackground(Color.WHITE);
        revalidate();
        repaint();
    }

    public boolean isSelected() {
        return isSelected;
    }

    public void imgLoad(String path) {
        if (imageCache.containsKey(path)) {
            imgTable.setIcon(imageCache.get(path));
        } else {
            new SwingWorker<ImageIcon, Void>() {
            @Override
            protected ImageIcon doInBackground() throws Exception {
                // Load ảnh đúng chuẩn từ resource
                InputStream input = getClass().getResourceAsStream(path);
                if (input == null) {
                    System.err.println("Không tìm thấy file ảnh: " + path);
                    return new ImageIcon(); // ảnh placeholder rỗng
                }

                BufferedImage bufImg = ImageIO.read(input);
                if (bufImg == null) {
                    System.err.println("Ảnh lỗi không đọc được: " + path);
                    return new ImageIcon();
                }

                int w = imgTable.getWidth() > 0 ? imgTable.getWidth() : 100;  // default 100 nếu chưa kịp render
                int h = imgTable.getHeight() > 0 ? imgTable.getHeight() : 100;

                Image scaledImg = bufImg.getScaledInstance(w, h, Image.SCALE_SMOOTH);
                return new ImageIcon(scaledImg);
            }

            @Override
            protected void done() {
                try {
                    ImageIcon icon = get();
                    imageCache.put(path, icon);
                    imgTable.setIcon(icon);
                    imgTable.revalidate();
                    imgTable.repaint();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }.execute();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        imgTable = new javax.swing.JLabel();
        tableName = new javax.swing.JLabel();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTable.setToolTipText("img");
        imgTable.setPreferredSize(new java.awt.Dimension(165, 140));
        imgTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTableMouseClicked(evt);
            }
        });

        tableName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tableName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableName.setText("jLabel6");
        tableName.setToolTipText("name");
        tableName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(imgTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTableMouseClicked
//        // TODO add your handling code here:
        isSelected = !isSelected;
        jPanel8.setBackground(isSelected ? Color.ORANGE : Color.WHITE); // Đổi màu nền

        if (isSelected) {
            tableLable.setText("Bàn " + ban.getSoBan() + " / " + loaiBan.getTenLB() + " (" + ban.getSoGhe() + ")");
            tableLable.setToolTipText(ban.getMaBan());

            // Tối ưu deselect
            if (getParent() != null) {
                for (Component comp : getParent().getComponents()) {
                    if (comp instanceof ItemTable) {
                        ItemTable item = (ItemTable) comp;
                        if (item != this && item.isSelected()) {
                            item.deselect();
                        }
                    }
                }
            }
        } else {
            tableLable.setText("");
            tableLable.setToolTipText("");
        }

        revalidate();
        repaint();
    }//GEN-LAST:event_imgTableMouseClicked

    private void tableNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNameMouseClicked
//        // TODO add your handling code here:
        isSelected = !isSelected;
        jPanel8.setBackground(isSelected ? Color.ORANGE : Color.WHITE); // Đổi màu nền

        if (isSelected) {
            tableLable.setText("Bàn " + ban.getSoBan() + " / " + loaiBan.getTenLB() + " (" + ban.getSoGhe() + ")");
            tableLable.setToolTipText(ban.getMaBan());

            // Tối ưu deselect
            if (getParent() != null) {
                for (Component comp : getParent().getComponents()) {
                    if (comp instanceof ItemTable) {
                        ItemTable item = (ItemTable) comp;
                        if (item != this && item.isSelected()) {
                            item.deselect();
                        }
                    }
                }
            }
        } else {
            tableLable.setText("");
            tableLable.setToolTipText("");
        }

        revalidate();
        repaint();

    }//GEN-LAST:event_tableNameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgTable;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel tableName;
    // End of variables declaration//GEN-END:variables
}
